export default {
    ROUTING_ERROR: 1,
    INVALID_TYPE_ERROR: 2,
    DATA_BASE_ERROR: 3,
    INVALID_PARAMS_ERROR: 4,
    BAD_REQUEST_ERROR: 5,
    AUTHENTICATION_ERROR: 6,
    AUTHORIZATION_ERROR: 7,
    INTERNAL_SERVER_ERROR: 8,
};